### ISSUE TITLE
[Feature] IndexScreen Profile

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_frontend_v2#14]
## Title

- [Feature] IndexScreen Profile

## Description

- FetchMe API 호출을 한 데이터를 기준으로 Profile 정보 보여주기

## TODO

- [x] : AppBar 햄버거 메뉴 퍼블리싱
- [x] : User Role 라벨 퍼블리싱
- [x] : User image 및 이름 퍼블리싱
- [x] : Drawer 퍼블리싱

## Watch out 

- TODO 외 다른 작업

**Comment by leewoooo** [comment]
Resolved with #15
