### ISSUE TITLE
[Feature] Splash Screen

### ISSUE THREAD

**Issue by leewoooo** [i-am-a-toy/pyc_frontend_v2#2]
## Title

- [Feature] Splash Screen

## Description

- 어플이 처음 시작될 때 Splash Screen을 구현, Splash Screen은 3초 지속된 이 후 Login Page로 이동한다.
  - secret storage에 토큰이 저장되어 있으면 index Page로 이동
  - 토큰이 저장되어 있지 않으면 Login 페이지로 이동 

## TODO

- [x] : splash screen 디자인하기
- [x] : splash screen의 기능을 추가하여 토큰을 검증 후 screen 이동하는 로직 구현
- [x] : login, index 빈 screen 구현하기

## Watch out 

- TODO 외 다른 작업

**Comment by leewoooo** [comment]
## Splash Screen

![Simulator Screen Shot - iPhone 12 Pro Max - 2023-01-29 at 23 30 36](https://user-images.githubusercontent.com/74294325/215333357-e6320917-f979-4739-aa72-a2218748df91.png)
